# **Assignment For Numpy**

Difficulty Level **Beginner**

In [3]:
import numpy as np

1. Import the numpy package under the name np

2. Create a null vector of size 10 

In [4]:
np.array(10)

array(10)

3. Create a vector with values ranging from 10 to 49

In [8]:
x=np.arange(10,50)

4. Find the shape of previous array in question 3

In [9]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [10]:
print(x.dtype)

int32


6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())

1.19.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [13]:
print(x.ndim)

1


8. Create a boolean array with all the True values

In [14]:
np.ones((10), dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [16]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [19]:
np.flip([1,2,3,4,5,6,7,8,9])

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [21]:
x= np.zeros((10))
x[4]=1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [34]:
arr = np.array((1, 2, 3, 4, 5))
arr = arr.astype(np.float64)
arr


array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [36]:
arr1 = np.array([1., 2., 3.,np.array([4., 5., 6.])])
arr2 = np.array([0., 4., 1.,np.array([7., 2., 12.])])
arr1*arr2

array([0.0, 8.0, 3.0, array([28., 10., 72.])], dtype=object)

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [51]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
comparison_array = (arr1==arr2)
comparison_array

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [53]:
arr = np.arange(0,10)
arr[(arr%2!=0)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

18. Replace all odd numbers to -1 from previous array

In [55]:
arr = np.arange(0,10)
arr[(arr%2!=0)]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [57]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [60]:
arr = np.ones((3,3))
arr[1,1]=0
arr

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [61]:
arr2d = np.array([1, 2, 3, [4, 5, 6], [7, 8, 9]])
arr2d[3][1]=12
arr2d

array([1, 2, 3, list([4, 12, 6]), list([7, 8, 9])], dtype=object)

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [64]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,0:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [68]:
arr2d = np.arange(0,9)
arr2d.resize(3,3)
arr2d[0:1,::]

array([[0, 1, 2]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [69]:
arr2d = np.arange(0,9)
arr2d.resize(3,3)
arr2d[1:2,1:2]

array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [71]:
arr2d = np.arange(0,9)
arr2d.resize(3,3)
arr2d[0:2,2:3]

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [76]:
arr = np.random.randn(100)
arr.resize(10,10)
print(arr.min())
arr.max()


-1.8346676602749155


2.212671071968558

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [78]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int32),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [125]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[np.where(names!='Will'),::]

array([[[-0.23463221,  0.55178709,  0.44596952,  0.62137859],
        [-0.06235188, -1.19464584, -0.72167091, -0.55760619],
        [ 1.19215657, -0.98769725, -0.60246048,  0.15040558],
        [ 0.93347764, -0.45751068, -1.04890214, -0.15013186],
        [-0.80925413, -0.20079416,  2.67006787,  0.78642669]]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [166]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
will = names!=('Will')
joe = names!=('Joe')
willjoe = data[np.where(will==joe)]
willjoe

array([[ 2.54060618,  1.71990032, -0.43708613, -0.65927495],
       [-0.3580708 , -0.21315952,  1.10961597, -0.01480165]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [82]:
arr2d = np.arange(1.,15)
arr2d.resize(5,3)
arr2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14.,  0.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [84]:
arr3d = np.arange(1.,17.)
arr3d.resize(2,2,4)
arr3d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [92]:
arr3d = np.arange(1.,17.)
arr3d.resize((2,2,4))
arr3d.swapaxes(0,1)


array([[[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]],

       [[ 5.,  6.,  7.,  8.],
        [13., 14., 15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [95]:
arr = np.random.rand(10)
arr = np.sqrt(arr)
check= np.where(arr<0.5)
arr[check]=0
arr

array([0.        , 0.71241887, 0.6061996 , 0.88803264, 0.64977294,
       0.52810855, 0.        , 0.        , 0.        , 0.931331  ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [97]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
newarray = np.maximum(arr1,arr2)
newarray

array([ 1.03209861,  0.74989559, -0.06814512, -0.21863953, -0.72985369,
        0.0159527 ,  0.70147543, -0.17387884,  3.01308209,  0.87061299,
       -0.75256472,  0.65105096])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [109]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will','Joe', 'Joe'])
x=np.unique(names)
x=np.sort(x)
x

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [193]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.delete(a,np.in1d(a,b))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [114]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
newColumn.resize(3,1)
sampleArray[:,1:2]=newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [115]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [118]:
arr = np.random.randn(20)
np.cumsum(arr)

array([ 0.50511401,  1.60815138,  2.25718951,  1.94409231,  3.04846436,
        3.21228237,  2.22821597,  2.11973744,  2.03178856,  1.79652322,
        1.53855905,  0.8836707 , -0.66071568,  0.55990173, -1.75821906,
       -2.96067704, -3.824397  , -3.7010278 , -3.67430789, -3.19397569])